#日本
province = { 
  id =	1200	
  naval_base = { size =	4	current_size = 	4	} 
} #元山港
province = { 
  id =	1178	
  naval_base = { size =	2	current_size = 	2	} 
}
province = { 
  id =	1393	
  naval_base = { size =	2	current_size = 	2	} 
}
province = { 
  id =	1196	
  air_base   = { size = 6       current_size =  6       }
  naval_base = { size = 6       current_size =  6       }
  supplypool = 5000
  oilpool    = 100
}#釜山
province = { 
  id =	1627	
  air_base   = { size = 2       current_size =  2       }
  naval_base = { size = 4       current_size =  4       }
  supplypool = 500
  oilpool    = 100
}#塞班
province = { 
  id =	3666
  air_base   = { size = 6       current_size =  6     }	
  naval_base = { size =	10	current_size = 	10	}
 }#长崎-佐世保
province = { 
  id =	1188
  air_base   = { size = 10      current_size =  10      }	
  naval_base = { size =	10	current_size = 	10	} 
}#广岛
province = { 
  id =	1189	
  air_base   = { size = 4       current_size =  4     }
  naval_base = { size =	10	current_size = 	10     } 
}#高知
province = { 
  id =	1180	
  air_base   = { size = 4       current_size =  4     }
}#仙台
province = { 
  id =	1187
  air_base   = { size = 10       current_size =  10     }	
  naval_base = { size =	10	current_size = 	10     } 
}#大阪
province = { 
  id =	1191
  air_base   = { size = 10       current_size =  10     }	
  naval_base = { size =	10	current_size = 	10     } 
}#鹿儿岛
province = { 
  id =	1186
  air_base   = { size = 10      current_size =  10      }	
  naval_base = { size =	10	current_size = 	10	}
 }#舞鹤
province = {
 id =	1185	
  air_base   = { size = 6       current_size = 6      }
  naval_base = { size =	6	current_size = 6      }
 }#名古屋
province = { 
  id =	1184
  air_base   = { size = 10      current_size =  10      }	
  naval_base = { size =	10	current_size = 	10	}
}#东京
province = { 
  id =	3656
  anti_air   = 5	
  naval_base = { size =	10	current_size = 	10	}
 }#横须贺
province =
{ id         = 1183
  air_base   = { size = 4      current_size = 4      }
  naval_base = { size = 8      current_size = 8      }
} #新泻
province = { 
  id =	1193	
  air_base   = { size = 4       current_size = 4        }    
  naval_base = { size = 6       current_size = 6        }
  supplypool = 1000
  oilpool = 100
}#冲绳
province = {
  id =	1608	
  naval_base = { size = 2       current_size = 2        }
  supplypool = 500
}#夸贾林环礁
province = { 
  id =	1601	
  supplypool = 500
}#埃尼威托克环礁
province = { 
id =	1613	
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 4 current_size = 4 }
  supplypool = 5000
  oilpool = 500
 }#特鲁克群岛
province =
{ id         = 1322
  air_base   = { size = 10      current_size =  10       }
  naval_base = { size = 10      current_size =  10       }
  supplypool = 1000
  oilpool    = 100
}  #高雄
province =
{ id         = 1323
  air_base   = { size = 8      current_size =  8       }
  naval_base = { size = 8      current_size =  8       }
}  #台北
province =
{ id       = 1199
  air_base = { size = 4 current_size = 4 }
}            # 汉城
province = { 
  id = 1599 
  naval_base = { size = 2 current_size = 2 }
  supplypool = 500 } # 硫磺岛
province = { 
  id = 1618 
  supplypool = 500 } # 乌利西环礁
province = { 
  id = 1621 
  naval_base = { size = 2      current_size =  2       }
  supplypool = 500 } # 帕劳
province = { 
  id = 1784 
  supplypool = 500  } # 小笠原群岛
province = { 
  id = 1785 
  supplypool = 500 } # Marcus Island
province = { 
  id = 1610 
  supplypool = 500 } # Ponape
province = { 
  id = 1605 
  naval_base = { size = 2      current_size =  2       }
  supplypool = 500  } # Majuro
province = { 
  id = 1685 
  naval_base = { size = 2      current_size =  2       }
  air_base   = { size = 2      current_size =  2       }
  supplypool = 500 } # 瓜达尔卡纳尔

#德国
province = { 
  id =	510
  air_base   = { size = 10      current_size =  10      }	
  naval_base = { size =	8	current_size = 	8	} }#柯尼斯堡
province = { 
  id =	296	
  naval_base = { size =	8	current_size = 	8	} }#罗斯托克
province = { 
  id =	90
  naval_base = { size =	10	current_size = 	10	} }#基尔
province = { 
  id =	80
  air_base   = { size = 10       current_size =  10     }	
  naval_base = { size =	10	 current_size =  10	} }#威廉港
province = { 
  id =	301	
  naval_base = { size =	6	current_size = 	6	} }#斯德丁
province =
{ id            = 67
  synthetic_oil = 1
  air_base      = { size = 10    current_size = 10 }
}            # 艾森
province =
{ id            = 75
landfort = 1 
synthetic_oil = 1
  air_base      = { size = 10    current_size = 10 }
}            # 科隆
province =
{ id       = 88
  air_base = { size = 10 current_size = 10 }
}            # 汉堡
province =
{ id       = 82
  air_base = { size = 10 current_size = 10 }
}            # Kassel
province =
{ id       = 300
  air_base = { size = 10 current_size = 10 }
} #柏林
province =
{ id       = 313
  air_base = { size = 10 current_size = 10 }
}            # 法兰克福
province =
{ id       = 314
  air_base = { size = 10 current_size = 10 }
} #斯图加特
province =
{ id       = 376
  air_base = { size = 10 current_size = 10 }
}            # 慕尼黑
province =
{ id       = 473
  air_base = { size = 10 current_size = 10 }
}            # 布雷斯瑙
province = { 
  id =	206	
  naval_base = { size =	2	current_size = 	2	} }#梅梅尔
province = {  
  id = 66 
  landfort = 1 } # Aachen
province = {  
id = 315 
landfort = 1 } # Freiburg
province = { 
id = 74 
landfort = 1  } # 萨尔布吕肯
province = { 
id = 1168 
landfort = 1 } # 卡尔斯鲁厄
province = {  
id = 3062 
landfort = 1  } # 凯撒斯劳滕
province = { 
id = 3061 
landfort = 1 } # 特里尔
province = { 
id = 510 
supplypool = 500
oilpool    = 200 } # 柯尼斯堡
province = { 
id = 310 
synthetic_rares = 1 } # Leipzig
province = { 
id = 224 
landfort = 1 } # 科布伦茨
province = { 
id = 3059 
landfort = 1 } # 克雷费尔德  
province = { 
id = 311
synthetic_oil = 1 } # 德累斯顿


#法国
province = { 
  id =	18	
  naval_base = { size =	4	current_size = 	4	} }#加莱
province = { 
  id =	1326	
  naval_base = { size =	4	current_size = 	4	} }#海防
province = { 
  id =	1333	
  naval_base = { size =	4	current_size = 	4	} }#岘港
province = { 
  id =	35
  naval_base = { size =	6	current_size = 	6	} }#南特
province = { 
  id =	38	
  air_base   = { size = 6 current_size = 6 }
  naval_base = { size = 10 current_size = 10 } }#瑟堡
province = { 
  id =	32	
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 } }#布雷斯特
province = { 
  id =	325	
  air_base   = { size = 6 current_size = 6 }
  naval_base = { size = 6 current_size = 6 } }#波尔多
province = { 
  id =	365	
  naval_base = { size =	10	current_size = 	10	} }#土伦
province =
{ id         = 364
  air_base   = { size = 10 current_size = 10 }	
  naval_base = { size =	10 current_size = 10 } 
}              # 马赛
province =
{ id       = 359
  air_base = { size = 6 current_size = 6 }
}            # Toulouse
province =
{ id       = 44
  air_base = { size = 4 current_size = 4 }
}            # 里尔
province =
{ id       = 56
  air_base = { size = 10 current_size = 10 }
}            # 巴黎
province =
{ id       = 62
  air_base = { size = 4 current_size = 4 }
}            # 欧塞尔
province =
{ id       = 72
  anti_air = 5
  air_base = { size = 8 current_size = 8 }
  landfort = 10
}            # Metz
province = { 
  id = 3046 
  landfort = 5 } # 萨瓦
province = {  
  id = 73 
  anti_air = 5 
  landfort = 10 } # Strasbourg
province = { 
  id = 316 
  anti_air = 5 
  landfort = 10 } # Mulhouse
province = {  
  id = 366 
  landfort = 5 } # Nice
province = { 
  id = 3045 
  landfort = 5 } # Grenoble
province = { 
  id = 528 
  air_base   = { size = 4 current_size = 4 }
  } # Lyon
province = { 
  id = 875 
  supplypool = 100 } # Cayenne
province = { 
  id =	1794	
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 4 current_size = 4 }
 }#贝鲁特
province = { 
  id =	939	
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 } }#突尼斯
province = { 
  id =	949	
  air_base   = { size = 6 current_size = 6 }
  naval_base = { size = 6 current_size = 6 } 
  supplypool = 500
  oilpool    = 500   }#阿尔及尔
province = { 
  id =	953	
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 4 current_size = 4 } }#奥兰
province = { 
  id =	958	
  air_base   = { size = 6 current_size = 6 }
  naval_base = { size = 6 current_size = 6 } }#卡萨布兰卡
province =
{ id         = 981
  naval_base = { size = 4 current_size = 4 }
}              # 达喀尔
province = { 
  id =	1337	
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 6 current_size = 6 }
  supplypool = 500
  oilpool    = 500  }#西贡
province = { 
  id =	1328	
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 4 current_size = 4 } }#河内
province = { 
  id = 1037 
  naval_base = { size = 4 current_size = 4 }
  supplypool = 200 
  oilpool    = 100 } # 吉布提
province = { 
  id = 1137 
  naval_base = { size = 2 current_size = 2 }
  supplypool = 200 
  oilpool    = 50 } # 马达加斯加
province = { 
  id = 1092 
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 4 current_size = 4 }
  supplypool = 200 
  oilpool    = 50 } # 利伯维尔
province = { 
  id = 1089 
  naval_base = { size = 2 current_size = 2 } } # 杜阿拉

#英国
province = { 
  id =	19
  air_base   = { size = 10 current_size = 10 }}#伦敦
province = { 
  id =	5
  air_base   = { size = 10 current_size = 10 }	
  naval_base = { size =	10 current_size = 10 } }#奥克尼群岛
province = { 
  id =	14	
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 } }#利物浦
province = { 
  id =	23	
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 } }#普利茅斯
province = { 
  id =	21	
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 } }#朴茨茅斯
province = { 
  id =	20	
  air_base    = { size = 10 current_size = 10 }
  naval_base  = { size = 10 current_size = 10 } }#多佛尔
province = { 
  id =	17	
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 } }#诺里奇
province =
{ id       = 9
  air_base = { size = 6 current_size = 6 }
  naval_base = { size = 6 current_size = 6 }
}            # 格拉斯哥
province = {  
  id = 16 
  air_base    = { size = 10 current_size = 10 }} # Birmingham
province = {  
  id = 3007 
  air_base    = { size = 10 current_size = 10 }} # 诺丁汉
province = { 
  id = 28 
  naval_base  = { size = 4 current_size = 4 }
  oilpool = 500 
  supplypool = 500 } # Belfast
province =
{ id       = 22
  naval_base = { size = 4 current_size = 4 }
}            # 布里斯托尔
province =
{ id       = 10
  naval_base = { size = 4 current_size = 4 }
  air_base = { size = 4 current_size = 4 }
}            # 爱丁堡
province = { 
  id =	31	
  air_base    = { size = 10 current_size = 10 }
  naval_base  = { size = 10 current_size = 10 }
  coastalfort = 5
  landfort = 5
  oilpool     = 500
  supplypool  = 500 }#马耳他
province = { 
  id =	348	
  air_base    = { size = 10 current_size = 10 }
  landfort    = 10
  oilpool     = 1000
  supplypool  = 1000 }#直布罗陀
province =
{ id       = 444
  naval_base = { size = 2 current_size = 2 }
}            # 尼克西亚
province =
{ id       = 873
  naval_base = { size = 4 current_size = 4 }
}            # 乔治敦
province = { 
  id = 900 
  air_base   = { size = 10 current_size = 10 }
  landfort    = 10 } # Suez
province = { 
  id = 901  
  oilpool = 200 
  supplypool = 200 } # Port Said
province = { 
  id =	906	
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 } }#亚历山大
province = { 
  id =	988	
  naval_base = { size = 2 current_size = 2 }
  oilpool    = 200
  supplypool = 200 }#弗里敦
province = { 
  id =	901	
  naval_base = { size =	2 current_size = 2 } }#塞得港
province = { 
  id =	1813	
  naval_base = { size =	2 current_size = 2 } }#亚丁
province = { 
  id =	1494	
  air_base   = { size = 6 current_size = 6 }
  naval_base = { size = 8 current_size = 8 } }#卡拉奇
province = { 
  id =	1505	
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 8 current_size = 8 } }#孟买
province = { 
  id =	1817	
  air_base   = { size = 6 current_size = 6 }
  naval_base = { size = 6 current_size = 6 }
  oilpool    = 500
  supplypool = 500  }#迪戈加西亚
province = { 
  id =	1517	
  air_base    = { size = 4 current_size = 4 }
  naval_base  = { size = 6 current_size = 6 }
  coastalfort = 2
  oilpool     = 200
  supplypool  = 200 }#科伦坡
province = { 
  id =	1299	
  air_base   = { size = 4       current_size =  4       }
  naval_base = { size =	8	current_size = 	8	} }#仰光
province = { 
id =	1353	
  air_base    = { size = 10 current_size = 10 }
  naval_base  = { size = 10 current_size = 10 }
  oilpool     = 500
  supplypool  = 500 }#新加坡
province =
{ id       = 1457
  air_base = { size = 4 current_size = 4 }
  naval_base  = { size = 4 current_size = 4 }
}            # 加尔各答
province =
{ id       = 1469
  air_base = { size = 4 current_size = 4 }
}            # Delhi
province = { 
  id =	866	
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 4 current_size = 4 }
  oilpool    = 100
  supplypool = 500  }#福克兰群岛
province = { 
  id =	576	
  air_base   = { size = 4       current_size =  4       }
  naval_base = { size =	4	current_size = 	4	} }#纽芬兰
province ={ 
  id         = 538
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 4 current_size = 4 }
  oilpool    = 100
  supplypool = 500
}              # 百慕大群岛
province =
{ id       = 1008
  naval_base = { size = 4 current_size = 4 }
}            #拉各斯
province =
{ id       = 993
  naval_base = { size = 2 current_size = 2 }
}            #阿比让
province =
{ id       = 1002
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 6 current_size = 6 }
}            #阿克拉
province =
{ id       = 1061
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 4 current_size = 4 }
}            # Mombasa
province =
{ id       = 1066
  air_base = { size = 2 current_size = 2 }
}            # Khartoum
province =
{ id       = 1296
  air_base = { size = 4 current_size = 4 }
}            # Mandalay
province =
{ id       = 404
  naval_base = { size = 4 current_size = 4 }
}            # 海法
province =
{ id       = 1799
  naval_base = { size = 2 current_size = 2 }
}            # 加沙
province =
{ id       = 1352
  naval_base = { size = 2 current_size = 2 }
}            # 吉隆坡
province =
{ id       = 3741
  naval_base = { size = 2 current_size = 2 }
}            # 斯里巴加湾
province =
{ id       = 1644
  naval_base = { size = 2 current_size = 2 }
}            # 古晋
province =
{ id       = 1642
  naval_base = { size = 2 current_size = 2 }
}            # 坤甸
province =
{ id       = 1508
  naval_base = { size = 2 current_size = 2 }
}            # 维杰亚瓦达
province =
{ id       = 1509
  naval_base = { size = 4 current_size = 4 }
}            # 马德拉斯
province =
{ id       = 1515
  naval_base = { size = 2 current_size = 2 }
}            # 马杜赖
province =
{ id       = 1466
  naval_base = { size = 4 current_size = 4 }
}            # 艾哈迈达巴德
province =
{ id       = 1822
  naval_base = { size = 2 current_size = 2 }
}            # 科威特
province =
{ id       = 1820
  naval_base = { size = 2 current_size = 2 }
}            # 多哈
province =
{ id       = 1504
  naval_base = { size = 2 current_size = 2 }
}            # 阿布扎比


#意大利
province = { 
  id =	519	
  air_base   = { size = 10      current_size =  10      }
  naval_base = { size =	10	current_size = 	10	}  }#罗马
province = { 
  id =	368	
  air_base   = { size = 10      current_size =  10      }
  naval_base = { size =	10	current_size = 	10	}
  landfort   = 5   }#热那亚
province =
{ id         = 3193
  landfort   = 5
}              # 库内奥
province =
{ id       = 370
  air_base = { size = 6 current_size = 6 }
}            # 米兰
province =
{ id       = 515
  air_base = { size = 10 current_size = 10 }
}            # Rome
province = { 
  id = 531 
  landfort = 5  } # Turin
province = { 
  id =	521	
  air_base = { size = 4         current_size =  4       }
  naval_base = { size =	10	current_size = 	10	} }#那不勒斯
province = { 
  id =	534
  air_base   = { size = 4       current_size =  4       }	
  naval_base = { size =	4	current_size = 	4	}
  oilpool    = 250
  supplypool = 1000  }#卡利亚里
province = { 
  id =	525
  air_base   = { size = 10      current_size =  10      }	
  naval_base = { size =	10      current_size =  10      } }#巴勒莫
province = { 
  id =	523
  air_base   = { size = 10      current_size =  10      }	
  naval_base = { size =	10	current_size = 	10	} }#塔兰托
province = { 
  id =	378	
  air_base   = { size = 10      current_size =  10      }
  naval_base = { size =	10	current_size = 	10	} }#威尼斯
province = { 
  id =	3200	
  naval_base = { size =	4	current_size = 	4	} }#的里亚斯特
province = { 
  id =	932
  air_base   = { size = 4       current_size =  4       }	
  naval_base = { size =	4	current_size = 	4	}
  oilpool    = 250
  supplypool = 1000  }#的黎波里
province = { 
  id =	924
  air_base   = { size = 4       current_size =  4       }	
  naval_base = { size =	4	current_size = 	4	} }#班加西
province = { 
  id =	919
  air_base   = { size = 2       current_size =  2       }	
  naval_base = { size =	2	current_size = 	2	}
  landfort   = 3  }#托普鲁克
province = { 
  id =	1033	
  air_base   = { size = 2       current_size =  2       }
  naval_base = { size =	2	current_size = 	2	}
  oilpool    = 100
  supplypool = 300  }#马萨瓦

province = { 
  id =	1056	
  air_base   = { size = 2       current_size =  2       }
  naval_base = { size =	4	current_size = 	4	}
  oilpool    = 100
  supplypool = 300  }#摩加迪沙

#苏联
province = { 
  id =	1372	
  air_base    = { size = 10     current_size =  10      }
  naval_base = { size =	10	current_size = 	10	}
  landfort    = 2
  coastalfort = 2  }#海参崴
province = { 
  id =	133
  air_base   = { size = 4       current_size =  4       }	
  naval_base = { size =	6	current_size = 	6	} }#摩尔曼斯克
province = { 
  id =	187	
  air_base    = { size = 10     current_size =  10      }
  naval_base  = { size = 10	current_size = 	10	}
  synthetic_rares = 1
  landfort    = 10
  coastalfort = 5  }#列宁格勒
province = { 
  id =	253
  air_base    = { size = 4      current_size =  4       }	
  naval_base = { size =	10	current_size = 	10	}
  landfort    = 5
  coastalfort = 5   }#塞瓦斯托波尔
province = { 
  id =	258	
  naval_base = { size =	4	current_size = 	4	} }#罗斯托夫
province = { 
  id =	255	
  naval_base = { size =	4	current_size = 	4	} }#新罗西斯克
province = { 
  id =	1172	
  naval_base = { size =	2	current_size = 	2	} }#勘察加
province = { 
  id =	1848
  air_base   = { size = 4       current_size =  4       }	
  naval_base = { size =	4	current_size = 	4	} }#巴统
province =
{ id          = 163
  air_base    = { size = 10 current_size = 10 }
  landfort    = 10
}               # Stalingrad
province =
{ id          = 175
  air_base    = { size = 10 current_size = 10 }
  landfort    = 10
}               # Moscow
province =
{ id       = 1567
  air_base = { size = 4 current_size = 4 }
}            # 乌法
province =
{ id       = 201
  air_base = { size = 4 current_size = 4 }
}            # 阿巴扎
province =
{ id       = 212
  air_base = { size = 6 current_size = 6 }
}            # 明斯克
province =
{ id       = 233
  air_base = { size = 4 current_size = 4 }
  naval_base = { size =	4 current_size = 4 }
}            # Odessa
province = 
{ id = 219 
  air_base = { size = 4 current_size = 4 }
}            # 斯摩棱斯克
province =
{ id       = 238
  air_base = { size = 8 current_size = 8 }
}            # Kiev
province =
{ id       = 248
  air_base = { size = 2 current_size = 2 }
}            # Kharkov
province =
{ id       = 258
  air_base = { size = 4 current_size = 4 }
}            # Rostov
province =
{ id       = 264
  air_base = { size = 4 current_size = 4 }
}            # Pavlovsk
province =
{ id       = 281
  air_base = { size = 2 current_size = 2 }
}            # 利佩茨克
province =
{ id       = 168
  air_base = { size = 2 current_size = 2 }
}            # Demyansk
province =
{ id       = 1384
  air_base = { size = 2 current_size = 2 }
}            # 赤塔
province =
{ id       = 1368
  air_base = { size = 4 current_size = 4 }
}            # Komsomolsk-na-Amure
province =
{ id       = 1783
  air_base = { size = 2 current_size = 2 }
}            # 基洛夫
province =
{ id       = 1572
  air_base = { size = 10 current_size = 10 }
}            # 叶卡捷琳
province =
{ id       = 176
  air_base = { size = 2 current_size = 2 }
}            # 雷宾斯克
province =
{ id       = 1544
  air_base = { size = 6 current_size = 6 }
}            # Tomsk
province =
{ id       = 1422
  air_base = { size = 6 current_size = 6 }
}            # 阿拉木图
province =
{ id       = 1552
  air_base = { size = 10 current_size = 10 }
}            # Omsk
province =
{ id       = 1548
  air_base = { size = 10 current_size = 10 }
}            # 新西伯利亚
province =
{ id       = 1574
  air_base = { size = 10 current_size = 10 }
}            # Chelyabinsk
province =
{ id       = 1577
  air_base = { size = 10 current_size = 10 }
}            # 奥尔斯克
province =
{ id       = 1827
  air_base = { size = 6 current_size = 6 }
}            # 奇斯托波尔
province =
{ id       = 1828
  air_base = { size = 10 current_size = 10 }
  synthetic_rares = 1
}            # 古比雪夫
province =
{ id       = 3530
  air_base = { size = 4 current_size = 4 }
}            # 谢苗诺夫
province =
{ id       = 1838
  air_base = { size = 4 current_size = 4 }
}            # Astrakhan
province =
{ id       = 1839
  air_base = { size = 4 current_size = 4 }
}            # 叶尔卲夫
province = { 
  id =	1907
  landfort    = 5
  air_base   = { size = 4      current_size =  4       } }#巴库
province = { 
  id =	3461
  air_base   = { size = 4       current_size =  4       } }#涅比特

#美国
province = { 
  id =	889
  air_base   = { size = 10       current_size =  10     }	
  landfort    = 10
  oilpool = 500
  supplypool = 1000  }#科隆
province = { 
id =	780	
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 } }#西雅图
province = { 
  id =	748	
  Naval_base = { size = 8 current_size = 8 } }#科珀斯克里斯蒂
province = { 
id =	765	
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 } }#旧金山
province = { 
id =	762	
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 } }#洛杉矶
province = { 
  id =	761	
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 } }#圣迭戈
province = { 
  id =	651	
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 } }#迈阿密
province = { 
  id =	633
  air_base   = { size = 10      current_size =  10      }	
  naval_base = { size =	10	current_size = 	10	} }#诺福克
province = { 
  id =	1786	
  air_base   = { size = 4 current_size = 4 }
  Naval_base = { size = 2 current_size = 2 }
  supplypool = 500 }#威克岛
province = { 
  id = 662 
  air_base   = { size = 4 current_size = 4 }
  Naval_base = { size = 4 current_size = 4 }
  supplypool = 500 } # 中途岛
province = { 
  id =	602	
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 } }#纽约
province = { 
  id =	600	
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 } }#波士顿
province = { 
  id =	680	
  Naval_base = { size = 6 current_size = 6 } }#新奥尔良
province = { 
  id =	676	
  Naval_base = { size = 6 current_size = 6 } }#莫比尔
province = { 
  id =	645	
  Naval_base = { size = 4 current_size = 4 } }#哥伦比亚
province = { 
  id =	604	
  air_base   = { size = 6 current_size = 6 }
  Naval_base = { size = 6 current_size = 6 } }#大西洋城
province = { 
  id =	603	
  air_base   = { size = 6 current_size = 6 }
  Naval_base = { size = 10 current_size = 10 } }#纽瓦克
province = { 
  id =	1624	
  air_base   = { size = 6 current_size = 6 }
  Naval_base = { size = 2 current_size = 2 }
  supplypool = 5000
  oilpool = 1000  }#关岛
province = { 
  id =	663	
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 }
  supplypool = 5000 
  oilpool = 1000  }#珍珠港
province = { 
  id = 553 
  supplypool = 1000 } # 朱诺
Province =
{ id       = 658
  air_base = { size = 4 current_size = 4 }
}            # 夏威夷
Province =
{ id       = 592
  air_base = { size = 4 current_size = 4 }
}            # 普拉词堡
province =
{ id       = 595
  air_base = { size = 4 current_size = 4 }
}            # Concord
province =
{ id         = 606
  air_base   = { size = 10 current_size = 10 }
}              # Washington D.C.
province =
{ id       = 614
  air_base = { size = 4 current_size = 4 }
}            # Pittsburgh
province =
{ id       = 616
  air_base = { size = 6 current_size = 6 }
}            # Detroit
province =
{ id       = 620
  air_base = { size = 10 current_size = 10 }
}            # Chicago
Province =
{ id       = 637
  air_base = { size = 4 current_size = 4 }
}            # Charlotte
province =
{ id       = 640
  air_base = { size = 4 current_size = 4 }
}            # Louisville
province =
{ id       = 644
  air_base = { size = 4 current_size = 4 }
}            # Charleston
Province =
{ id       = 648
  air_base = { size = 4 current_size = 4 }
}            # Jacksonville
province =
{ id       = 670
  air_base = { size = 4 current_size = 4 }
}            # Atlanta
Province =
{ id       = 673
  air_base = { size = 4 current_size = 4 }
}            # Memphis
Province =
{ id       = 678
  air_base = { size = 4 current_size = 4 }
}            # Biloxi
province =
{ id       = 684
  air_base = { size = 6 current_size = 6 }
}            # Little Rock
province =
{ id       = 689
  air_base = { size = 4 current_size = 4 }
}            # St. Louis
province =
{ id       = 692
  air_base = { size = 6 current_size = 6 }
}            # Des Moines
province =
{ id       = 693
  air_base = { size = 4 current_size = 4 }
}            # Minneapolis
province =
{ id       = 707
  air_base = { size = 4 current_size = 4 }
}            # Denver
Province =
{ id       = 713
  air_base = { size = 4 current_size = 4 }
}            # Oklahoma City
province =
{ id       = 716
  air_base = { size = 10 current_size = 10 }
}            # Houston
Province =
{ id       = 725
  air_base = { size = 4 current_size = 4 }
}            # Santa Fe
province =
{ id       = 730
  air_base = { size = 4 current_size = 4 }
}            # Phoenix
province =
{ id       = 733
  air_base = { size = 10 current_size = 10 }
}            # Salt Lake City
province =
{ id       = 789
  air_base = { size = 4 current_size = 4 }
}            # Omaha
province = { 
  id =	551	
  air_base   = { size = 2 current_size = 2 }
  Naval_base = { size = 4 current_size = 4 }
  supplypool = 500
  oilpool = 100  }#阿拉斯加半岛
province = { 
  id =	895	
  Naval_base = { size = 2 current_size = 2 }
  supplypool = 500
  oilpool = 100  }#波多黎各
province = { 
  id = 895 
  supplypool = 100 } # Puerto Rico
province = { 
  id = 1408 
  supplypool = 500 } # Attu Island
province = { 
  id = 1756 
  supplypool = 100 } # Samoa
province = { 
  id = 1762 
  supplypool = 100 } # Phoenix Island
province = { 
  id = 1765 
  supplypool = 100 } # Palmyra
province = { 
  id = 1766 
  supplypool = 100  } # Johnson Island

#爱沙尼亚
province = { 
  id =	194
  air_base = { size =	2	current_size = 	2	}	
  naval_base = { size =	2	current_size = 	2	} }#塔林

#拉脱维亚
province = { 
  id =	197
  air_base = { size =	2	current_size = 	2	} 	 
  naval_base = { size =	4	current_size = 	4	} }#里加

#立陶宛
province = {  
  id =	207	
  air_base = { size =	2	current_size = 	2	} }#考纳斯

#波兰
province = { 
  id =	303	
  air_base = { size =	4	current_size = 	4	}
  naval_base = { size =	8	current_size = 	8	} }#但泽
province = { 
  id =	307	
  air_base = { size =	4	current_size = 	4	} }#波兹南
province = { 
  id =	485	
  air_base = { size =	8	current_size = 	8	} }#华沙
province = { 
  id =	504	
  air_base = { size =	2	current_size = 	2	} }#布列斯特
province = {
  id =	501	
  air_base = { size =	4	current_size = 	4	} }#利沃夫

#芬兰
province = { 
  id =	141	
  air_base = { size =	4	current_size = 	4	}
  naval_base = { size =	4	current_size = 	4	}   }#图尔库
province = { 
  id =	142
  air_base = { size =	8	current_size = 	8	}	
  naval_base = { size =	10	current_size = 	10	}  }#赫尔辛基
province = { 
  id =	132	
  naval_base = { size =	4	current_size = 	4	} }#贝柴摩
province = { 
  id = 145  
  naval_base = { size =	2	current_size = 	2	}
  landfort = 2 } # 维堡
province = { 
  id =	4091	
  air_base = { size =	2	current_size = 	2	}
  naval_base = { size =	4	current_size = 	4	}  }#汉科

#瑞典
province = { 
  id =	127	
  air_base = { size =	2	current_size = 	2	} 
  naval_base = { size =	4	current_size = 	4	} }#吕勒奥
province = { 
  id =	101
  air_base = { size =	4	current_size = 	4	}	
  naval_base = { size =	10	current_size = 	10	}  }#斯德哥尔摩
province = { 
  id =	95
  naval_base = { size =	8	current_size = 	8	}  }#卡尔马
province = { 
  id =	98
  air_base = { size =	2	current_size = 	2	}	
  naval_base = { size =	8	current_size = 	8	}  }#哥德堡

#挪威
province = { 
  id =	107	
  air_base = { size =	4	current_size = 	4	}
  naval_base = { size =	10	current_size = 	10	} }#奥斯陆
province = { 
  id =	110	
  air_base = { size =	2	current_size = 	2	}
  naval_base = { size =	8	current_size = 	8	}  }#卑尔根
province = { 
  id =	125	
  naval_base = { size =	8	current_size = 	8	} }#纳尔维克
province = { 
  id =	129	
  naval_base = { size =	4	current_size = 	4	} }#瓦尔德
#丹麦
province = { 
  id =	1
  air_base = { size =	8	current_size = 	8	}	
  naval_base = { size =	8	current_size = 	8	} }#雷克雅未克
province = { 
  id =	92	
  naval_base = { size =	6	current_size = 	6	} }#奥尔胡斯
province = { 
  id =	3115	
  naval_base = { size =	6	current_size = 	6	} }#埃斯比约
province = { 
  id =	294
  air_base = { size =	10	current_size = 	10	}	
  naval_base = { size =	10	current_size = 	10	} }#哥本哈根


#西班牙
province = { 
  id =	357	
  air_base = { size =	4	current_size = 	4	} 
  naval_base = { size =	10	current_size = 	10	} }#巴塞罗那
province = { 
  id =	354
  air_base = { size =	2	current_size = 	2	}	
  naval_base = { size =	6	current_size = 	6	} }#巴伦西亚
province = { 
  id =	535
  naval_base = { size =	4	current_size = 	4	} }#马略卡岛
province = { 
  id =	334	
  air_base = { size =	4	current_size = 	4	} 
  naval_base = { size =	6	current_size = 	6	} }#拉科鲁尼亚
province = { 
  id =	963
  air_base = { size =	2	current_size = 	2	}	
  naval_base = { size =	2	current_size = 	2	} }#拉斯帕尔马斯
province = {
  id =	957
  air_base = { size =	2	current_size = 	2	}	
  naval_base = { size =	2	current_size = 	2	} }#休达
province = { 
  id =	347	
  air_base = { size =	4	current_size = 	4	}  }#塞维利亚
province = { 
  id =	3264	
  naval_base = { size = 8 current_size = 8 }  }#加迪斯
province = {
  id =	341	
  air_base = { size =	10	current_size = 	10	} }#马德里

#葡萄牙
province = { 
  id =	336	
  air_base = { size =	10	current_size = 	10	}
  naval_base = { size =	10	current_size = 	10	} }#里斯本
province = { 
  id =	335	
  naval_base = { size =	4	current_size = 	4	} }#波尔图
province = { 
  id =	1867	
  air_base = { size =	2	current_size = 	2	}
  naval_base = { size =	2	current_size = 	2	} }#亚速尔群岛
province = { 
  id =	983	
  naval_base = { size =	4	current_size = 	4	} }#比绍
province = { 
  id =	1090	
  naval_base = { size =	2	current_size = 	2	} }#圣多美
province = { 
  id =	1096
  air_base = { size =	2	current_size = 	2	}	
  naval_base = { size =	4	current_size = 	4	} }#罗安达
province = { 
  id =	1122	
  air_base = { size =	2	current_size = 	2	}
  naval_base = { size =	4	current_size = 	4	} }#伊尼扬巴内
province = {  
  id =	1658	
  naval_base = { size =	2	current_size = 	2	} }#东帝汶
province = {  
  id =	1130	
  naval_base = { size =	2	current_size = 	2	} }#贝拉
province = {  
  id =	1122	
  naval_base = { size =	4	current_size = 	4	} }#马普托

#荷兰
province = { 
  id =	47
  air_base = { size =	10	current_size = 	10	}	
  naval_base = { size =	10	current_size = 	10	} }#阿姆斯特丹
province = { 
  id =	46	
  naval_base = { size =	10	current_size = 	10	} }#鹿特丹
province = { 
  id = 3057 
  landfort = 1  } # 马斯特里赫特
province = {
  id =	1640	
  air_base = { size =	2	current_size = 	2	}
  naval_base = { size =	2	current_size = 	2	} }#望加西
province = {  
  id =	1632	
  naval_base = { size =	4	current_size = 	4	} }#泗水
province = { 
  id =	1628
  air_base   = { size = 2       current_size =  2       }	
  naval_base = { size =	6	current_size = 	6	}
  oilpool    = 50
  supplypool = 500   }#雅加达
province =
{ id       = 1355
  naval_base = { size = 2 current_size = 2 }
}            # 棉兰
province =
{ id       = 1358
  naval_base = { size = 2 current_size = 2 }
}            # 巨港
province =
{ id       = 1641
  naval_base = { size = 2 current_size = 2 }
}            # 马辰
province =
{ id       = 1653
  naval_base = { size = 2 current_size = 2 }
}            # 万鸦老
province =
{ id       = 1640
  naval_base = { size = 4 current_size = 4 }
}            # 望加锡
province =
{ id       = 1665
  naval_base = { size = 4 current_size = 4 }
}            # 荷兰迪亚
province =
{ id       = 1674
  naval_base = { size = 2 current_size = 2 }
}            # 马老奇
province = { 
  id =	874	
  naval_base = { size = 2 current_size = 2 } }#帕拉马里博

#比利时
province = { 
  id =	45	
  naval_base = { size =	4	current_size = 	4	} }#根特
province = { 
  id =	1095	
  air_base   = { size = 2       current_size =  2       }
  naval_base = { size =	4	current_size = 	4	}
  oilpool    = 10
  supplypool = 50   }#巴纳纳
province =
{ id       = 50
  air_base = { size = 4 current_size = 4 }
}            # Antwerp
province =
{ id       = 51
  air_base = { size = 10 current_size = 10 }
}            # Brussels
province = { 
  id = 68 
  anti_air = 3  landfort = 3  } # 烈日

#爱尔兰
province = { 
  id =	30	
  air_base = { size =	4	current_size = 	4	}
  naval_base = { size = 8       current_size =  8       }   }#都柏林

#希腊
province = { 
  id =	396	
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 2 current_size = 2 } }#伊拉克利翁
province = { 
  id =	401	
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 10 current_size = 10 } }#雅典
province = {  
  id = 411 
  naval_base = { size = 2 current_size = 2 } } # Salonika

#土耳其
province = { 
  id =	409	
  landfort   = 10
  air_base   = { size = 6 current_size = 6 }
  naval_base = { size = 10 current_size = 10 } }#伊斯坦布尔
province = { 
  id =	448	
  air_base = { size =	6	current_size = 	6	} }#安卡拉
province = { 
  id =	437	
  naval_base = { size = 4 current_size = 4 } }#伊兹米特
province = { 
  id =	3941	
  naval_base = { size = 4 current_size = 4 } }#奥斯曼尼耶
#南斯拉夫
province = { 
  id =	384	
  naval_base = { size = 4 current_size = 4 } }#斯普利特
province = {
  id =	453	
  air_base = { size =	4	current_size = 	4	} }#贝尔格莱德

#罗马尼亚
province = {
  id =	423	
  air_base = { size =	2 current_size = 2 }
  naval_base = { size = 4 current_size = 4 }  }#康斯坦察
province = {
  id =	435	
  naval_base = { size = 4 current_size = 4 }  }#伊兹梅尔
province = { 
  id =	424
  air_base = { size =	4	current_size = 	4	} }#布加勒斯特

#保加利亚
province = { 
  id =	422
  naval_base = { size = 4       current_size =  4       } }#瓦尔纳
province = { 
  id = 417 
  air_base = { size =	4	current_size = 	4	} } # Sofia


#阿尔巴尼亚
province = { 
  id =	390	
  naval_base = { size = 4       current_size =  4       } }#地拉那

#瑞士
province = { 
  id = 372 
  landfort = 5  } # Chur
province = { 
  id = 530 
  landfort = 5  } # Geneva
province =
{ id       = 532
  air_base = { size = 4 current_size = 4 }
  landfort = 5
}            # Bern
province = { 
  id = 533 
  landfort = 5  }
province = { 
  id = 3192
  landfort = 5  }
#匈牙利
province = { 
  id =	457	
  air_base = { size = 8	    current_size = 8	} }#布达

#巴拉圭
province = { 
  id =	837  
  air_base = { size =	2	current_size = 	2	} }#亚松森

#奥地利
province = { 
  id =	462	
  air_base = { size =	6	current_size = 	6	} }#萨尔斯堡
province = {
  id =	463
  air_base = { size =	10	current_size = 	10	} }#维也纳

#捷克
province = { 
  id =	469	
  air_base = { size =	4	current_size = 	4	} }#布拉格
province = { 
  id =	476	
  air_base = { size =	2	current_size = 	2	}
  landfort = 5  }#布拉迪斯拉法
province = { 
  id = 466 
  landfort = 5 } # 海布
province = {
  id = 467 
  landfort = 5 } # 兹诺伊莫
province = { 
  id = 471 
  landfort = 5 } # 乌斯季
province = { 
  id = 472 
  landfort = 5 } # 利贝雷茨
province = { 
  id = 3165 
  landfort = 5 } # 克尼格雷茨
province = { 
  id = 3163 
  landfort = 5  } # 奥帕瓦
province = { 
  id = 3169 
  landfort = 5 } # 波斯米亚林山
province = { 
  id = 3170
  landfort = 5 } # 捷克克鲁姆洛夫

#阿根廷
province = { 
  id =	853	
  air_base = { size =	2	current_size = 	2	}
  naval_base = { size = 6 current_size = 6 } }#布兰卡港
province = { 
  id =	667	
  air_base = { size =	4	current_size = 	4	}
  naval_base = { size = 8 current_size = 8 } }#布宜诺斯艾利斯
province = { 
  id =	858	
  naval_base = { size = 4 current_size = 4 } }#海军准将城

#乌拉圭
province = { 
  id =	849	
  naval_base = { size = 4 current_size = 4 } }#蒙得维的亚

#巴西
province = { 
  id =	848	
  naval_base = { size = 4 current_size = 4 } }#阿雷格里港
province = { 
  id =	886	
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 6 current_size = 6 } }#圣保罗
province = { 
  id =	885	
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 6 current_size = 6 } }#里约热内卢
province = { 
  id =	884	
  naval_base = { size = 4 current_size = 4 } }#维多利亚
province = { 
  id =	881	
  naval_base = { size = 4 current_size = 4 } }#累西腓
province = { 
  id =	876	
  naval_base = { size = 2 current_size = 2 } }#马卡帕

#厄瓜多尔
province = {
  id =	814	
  naval_base = { size = 2       current_size =  2 } }#瓜亚基尔

#哥伦比亚
province = { 
  id =	803	
  naval_base = { size = 2 current_size = 2 } }#巴兰基亚

province = { 
  id =	4029	
  naval_base = { size = 2 current_size = 2 } }#卡利

#秘鲁
province = { 
  id =	830	
  naval_base = { size = 2 current_size = 2 }  }#利马

#智利
province = { 
  id =	840	
  air_base = { size = 2  current_size = 2 }
  naval_base = { size = 8 current_size = 8 }  }#圣地亚哥
province = { 
  id =	856	
  naval_base = { size = 2 current_size = 2 }  }#蒙特港

#巴拿马
province = { 
  id =	888	
  naval_base = { size = 2 current_size = 2 } }#巴拿马城

province = { 
  id =	4024	
  naval_base = { size = 2 current_size = 2 } }#博卡斯—德尔托罗

#尼加拉瓜
province = {
  id =	539	
  naval_base = { size = 1 current_size = 1 } }#马那瓜

#玻利维亚
province = { 
  id =	832	
  air_base = { size =	2	current_size = 	2	} }#拉各斯

#委内瑞拉
province = { 
  id =	804	
  naval_base = { size = 6 current_size = 6 } }#马拉开波
province = { 
  id =	811	
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 4 current_size = 4 } }#加拉加斯

#多米尼加
province = { 
  id =	894	
  naval_base = { size = 4 current_size = 4 } }#圣多明各

#海地
province = { 
  id =	892	
  air_base = { size = 2	current_size = 2 }
  naval_base = { size = 4 current_size = 4 } }#太子港

#加拿大
province = {
  id =	579	
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 10 current_size = 10 } }#哈利法克斯
province = { 
  id =	581	
  air_base   = { size = 6 current_size = 6 }
  naval_base = { size = 4 current_size = 4 } }#圣约翰
province = { 
  id =	586	
  air_base   = { size = 6 current_size = 6 }
  naval_base = { size = 8 current_size = 8 } }#魁北克
province = { 
  id =	541	
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 } }#温哥华
province = { 
  id = 589 
  air_base   = { size = 4 current_size = 4 } } # Toronto
province = {
  id =	585	
  air_base = { size = 4 current_size = 4 } }#蒙特利尔
province = { 
  id =	588	
  air_base = { size = 4 current_size = 4 } }#渥太华
province = {
  id =	569	
  air_base = { size = 2 current_size = 2 } }#温尼伯
province = { 
  id =	797	
  air_base = { size = 2 current_size = 2 } }#卡尔加里
province = { 
  id =	566	
  naval_base = { size = 4 current_size = 4 } }#丘吉尔港

#墨西哥
province = { 
  id =	752	
  air_base   = { size = 2 current_size = 2 } }#墨西哥城
province = { 
  id =	738	
  naval_base = { size = 2 current_size = 2 } }#拉巴斯
province = { 
  id =	751	
  naval_base = { size = 4 current_size = 4 } }#瓜达拉哈拉
province = { 
  id =	749	
  naval_base = { size = 4 current_size = 4 } }#坦皮科

#南非
province = { 
  id =	1108	
  naval_base = { size = 4 current_size = 4 } }#沃尔维斯港
province = { 
  id =	1116	
  air_base = { size =	4 current_size = 4	}
  naval_base = { size = 8 current_size = 8 } }#开普敦
province = { 
  id =	1119	
  naval_base = { size = 4 current_size = 4 } }#德班
province = { 
  id =	1117	
  naval_base = { size = 2 current_size = 2 } }#伊丽莎白港

#利比里亚
province = { 
  id =	992	
  air_base = { size =	2	current_size = 2 }
  naval_base = { size = 2       current_size = 2 } }#蒙罗维亚

#澳大利亚
province = { 
  id =	1712	
  air_base = { size =	10	current_size = 	10 }
  naval_base  = { size = 10     current_size = 10 } }#珀斯
province = { 
  id =	1703	
  air_base = { size =	8	current_size = 	8	}
  naval_base = { size = 8       current_size = 8 }  }#达尔文
province = { 
  id =	1679	
  air_base = { size =	8	current_size = 	8  }
  naval_base = { size = 8       current_size =  8  }
  oilpool    = 100
  supplypool = 500  } #莫尔兹比港
province = {
  id =	1670	
  air_base = { size =	6 current_size = 6 }
  naval_base = { size = 4 current_size = 4 }  }#拉包尔
province = { 
  id =	1722	
  air_base = { size =	8 current_size = 8 }
  naval_base  = { size = 8 current_size = 8 } }#布里斯班
province = {
  id =	1727	
  naval_base  = { size = 10 current_size = 10 }
  air_base    = { size = 10 current_size = 10 } }#悉尼
province = { 
  id =	1730	
  air_base = { size =	2	current_size = 	2     }
  naval_base = { size = 8       current_size =  8     } 
 }#墨尔本

province = { 
  id =	1728	
  air_base = { size =	4	current_size = 	4	} }#堪培拉
province = { 
  id =	1733	
  naval_base = { size = 6       current_size = 6 }  } #阿德莱德
province = { 
  id =	1722	
  naval_base = { size = 4       current_size = 4 }  } #布里斯班
province = { 
  id =	1696	
  naval_base = { size = 4       current_size = 4 }  } #汤斯维尔
#新西兰
province = { 
  id =	1871	
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 4 current_size = 4 } }#惠灵顿

province = { 
  id = 1868 
  naval_base = { size = 4 current_size = 4 } } # Auckland

province = { 
  id = 1872 
  naval_base = { size = 4 current_size = 4 } } # 克赖斯特彻奇

#阿曼
province = { 
  id =	1819	
  naval_base = { size = 4 current_size = 4 }  }#马斯喀特

#伊拉克
province =
{ id         = 1823
  naval_base = { size = 4 current_size = 4 }
}              # Basrah

#伊朗
province = {
  id =	1497	
  naval_base = { size = 4 current_size = 4 }   }#阿巴斯港
#伊朗
province = {
  id =	1825	
  naval_base = { size = 6 current_size = 6 }   }#霍梅尼港

#泰国
province = { 
  id =	1343	
  air_base = { size = 2	current_size =2	}
  naval_base = { size = 6  current_size = 6 }  }#曼谷
province = { 
  id =	1348	
  naval_base = { size = 2  current_size = 2 }  }#宋卡港

#菲律宾
province = { 
  id =	1737	
  air_base = { size =	2     current_size = 2 }
  naval_base = { size = 8     current_size = 8 }  }#马尼拉
province =
{ id       = 1748
  naval_base = { size = 2 current_size = 2 }
}            # 三宝颜

#古巴
province =
{ id         = 654
  naval_base = { size = 4 current_size = 4 }
}              # Havana
province = { 
  id =	657	
  air_base = { size =	4	current_size = 	4	}
  naval_base = { size =	6	current_size = 	6	}
  supplypool = 3000
  oilpool = 300  }#关塔那摩美军租借

#洪都拉斯
province =
{ id         = 806
  naval_base = { size = 2 current_size = 2 }
}              # 圣佩德罗苏拉

#危地马拉
province =
{ id         = 665
  naval_base = { size = 2 current_size = 2 }
}              # 巴里奥斯港

#沙特
province =
{ id         = 1821
  naval_base = { size = 4 current_size = 4 }
}              # 达曼
province =
{ id         = 3911
  naval_base = { size = 2 current_size = 2 }
}              # 麦加
province =
{ id         = 1030
  naval_base = { size = 2 current_size = 2 }
}              # 苏丹

#中国
province = { 
  id =	1315	
  air_base    = { size = 6 current_size = 6 }
  naval_base  = { size = 10 current_size = 10 }
  oilpool     = 1000
  supplypool  = 1000 }#香港
province = { 
  id =	1316	
  naval_base = { size = 2	current_size = 2   }
 }#澳门
province = { 
  id =	1204	
  naval_base = { size = 8	current_size = 8   }
 }#天津
province = { 
  id =	1217	
  naval_base = { size = 6	current_size = 6   }
 }#连云
province = { 
  id =	1240	
  naval_base = { size = 6	current_size = 6   }
 }#温州
province = { 
  id =	1219	
  naval_base = { size = 4	current_size = 4   }
 }#南通
province = { 
  id =	1239	
  naval_base = { size = 6	current_size = 6   }
 }#宁波
province = { 
  id =	1325	
  naval_base = { size = 2	current_size = 2   }
 }#钦县
province = { 
  id =	1247	
  naval_base = { size = 4	current_size = 4   }
 }#厦门
province = { 
  id =	1248	
  naval_base = { size = 4	current_size = 4   }
 }#汕头
province = { 
  id =	2930	
  naval_base = { size = 10 current_size = 10   } 
  coastalfort = 5
  supplypool = 1000
  oilpool    = 500
}#旅顺港
province = { 
  id =	1202	
  air_base   = { size = 4 current_size = 4   }
  naval_base = { size =	4 current_size = 4   } 
}#大连
province = { 
  id = 1203 
  air_base   = { size = 4 current_size = 4   }
  naval_base = { size = 4 current_size = 4   } 
  supplypool = 4000 
  oilpool = 2000 } # 唐山
province = { 
  id = 1215 
  naval_base = { size = 10 current_size = 10   } 
  air_base   = { size = 6 current_size = 6 }
} # 青岛
province = { 
  id = 2861 
  naval_base = { size = 6 current_size = 6   } 
} # 威海卫
province =
{ id       = 1319
  air_base = { size = 4 current_size = 4 }
} #南宁
province =
{ id       = 1225
  air_base = { size = 4 current_size = 4 }
} #太原
province =
{ id       = 1255
  air_base = { size = 4 current_size = 4 }
} #长沙
province =
{ id       = 1228
  air_base = { size = 4 current_size = 4 }
} #郑州
province =
{ id       = 1320
  naval_base = { size = 6 current_size = 6 }
} #湛江
province =
{ id         = 1313
  air_base   = { size = 6 current_size = 6 }
  naval_base = { size = 10 current_size = 10 }
} #广州
province =
{ id         = 1321
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 4 current_size = 4 }
} #琼山
province =
{ id         = 1237
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
} #上海
province =
{ id         = 1395
  naval_base = { size = 2 current_size = 2 }
} #營口  
province =
{ id         = 1276
  air_base = { size = 2 current_size = 2 }
} #兰州
province =
{ id       = 1238
  air_base = { size = 6 current_size = 6 }
} #杭州
province =
{ id       = 1244
  naval_base = { size = 2 current_size = 2 }
} #福州
province =
{ id       = 1251
  air_base = { size = 6 current_size = 6 }
} #南昌
province =
{ id       = 1360
  air_base = { size = 4 current_size = 4 }
} #成都
province =
{ id       = 1235
  air_base = { size = 6 current_size = 6 }
} #南京
province =
{ id       = 1232
  air_base = { size = 6 current_size = 6 }
} #汉口
province =
{ id       = 1269
  air_base = { size = 8 current_size = 8 }
} #西安
province =
{ id       = 1205
  air_base = { size = 10 current_size = 10 }
}  #北平
province =
{ id       = 1216
  air_base = { size = 6 current_size = 6 }
} #济南
province =
{ id       = 1379
  air_base = { size = 4 current_size = 4 }
} #哈尔滨
province =
{ id       = 1390
  air_base = { size = 6 current_size = 6 }
} #新京
province =
{ id       = 1389
  air_base = { size = 4 current_size = 4 }
} #沈阳
province =
{ id       = 1318
  naval_base = { size = 2 current_size = 2 }
} #茂名
province =
{ id       = 1258
  air_base = { size = 4 current_size = 4 }
} #桂林
province =
{ id       = 1307
  air_base = { size = 4 current_size = 4 }
} #昆明
province =
{ id       = 1364
  air_base = { size = 4 current_size = 4 }
} #贵阳
province =
{ id       = 1231
  air_base = { size = 2 current_size = 2 }
} #襄阳
province =
{ id       = 1271
  air_base = { size = 2 current_size = 2 }
} #延安
province =
{ id       = 1745
  air_base = { size = 2 current_size = 2 }
} #莱特岛