##############################
# Country definition for u18 #
##############################

#####################
# Country main data #
#####################

country =
{ tag                    = u18
  intrinsic_gov_type     = paternal_autocrat
  # Resource Reserves
  energy                 = 200
  metal                  = 200
  rare_materials         = 100
  oil                    = 100
  supplies               = 100
  money                  = 50
  capital                = 4135 # ºÚ°µ

	research_mod = 1.00

  manpower               = 0
  dissent                = 0
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 4
    political_left    = 5
    freedom           = 3
    free_market       = 3
    professional_army = 10
    defense_lobby     = 5
    interventionism   = 1
  }

  # ºÚ°µ
  nationalprovinces      = { 4135 }
  ownedprovinces         = { 4135 }
  #
  controlledprovinces    = { 4135 }
  # u18
  # ROTW Minor Tech '36
  # Group E 1936 techs
  # ######################
  # GW fighter
  techapps               = {  }
  diplomacy =
  {
  }
  # ######
  # u18
  # ######

}
