##############################
# Country definition for U18 #
##############################

country = {
  tag                = U18
  intrinsic_gov_type = paternal_autocrat
  capital            = 4135 # ÁôÄáÍôµºÓ°×Ó
  manpower           = 0
  research_mod           = 1
  # Resource Reserves
  energy         = 200
  metal          = 200
  rare_materials = 100
  oil            = 100
  supplies       = 100
  money          = 50

  nationalprovinces      = { 4135 }
  ownedprovinces         = { 4135 }
  controlledprovinces    = { 4135 }

  techapps               = { 1010 1020 1030 1040 1050 1890 2720 1900 2800 1910 2810 5310 66500 66510 78100 1060 }

  policy = {
    date              = { year = 0 month = january day = 0 }
    democratic        = 4
    political_left    = 5
    freedom           = 3
    free_market       = 3
    professional_army = 10
    defense_lobby     = 5
    interventionism   = 1
  }
}
